
language: node_js

node_js:
  - '6'
  - '8'
  - '10'

cache: npm

before_script:
  - npm install coveralls

script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js